version: '3.9'

services:
  dapr-placement:
    image: "daprio/placement"
    command: ["./placement", "--port", "50005"]
    ports:
      - "50005:50005"
    networks:
      - dapr-network

  content-service:
    build: .
    environment:
      - APP_MODULE=jokes-app.content_service:app
      - APP_PORT=8001
    ports:
      - "8001:8001"
    networks:
      - dapr-network

  dapr-content-service:
    image: "daprio/daprd:latest"
    command: >
      ./daprd --app-id content-service --app-port 8001 --dapr-http-port 3500 --placement-host-address dapr-placement:50005
    depends_on:
      - content-service
      - dapr-placement
    ports:
      - "3500:3500"
    networks:
      - dapr-network

  rating-service:
    build: .
    environment:
      - APP_MODULE=jokes-app.rating_service:app
      - APP_PORT=8002
    ports:
      - "8002:8002"
    networks:
      - dapr-network

  dapr-rating-service:
    image: "daprio/daprd:latest"
    command: >
      ./daprd --app-id rating-service --app-port 8002 --dapr-http-port 3501 --placement-host-address dapr-placement:50005
    depends_on:
      - rating-service
      - dapr-placement
    ports:
      - "3501:3501"
    networks:
      - dapr-network

  ranking-service:
    build: .
    environment:
      - APP_MODULE=jokes-app.ranking_service:app
      - APP_PORT=8003
    ports:
      - "8003:8003"
    networks:
      - dapr-network

  dapr-ranking-service:
    image: "daprio/daprd:latest"
    command: >
      ./daprd --app-id ranking-service --app-port 8003 --dapr-http-port 3502 --placement-host-address dapr-placement:50005
    depends_on:
      - ranking-service
      - dapr-placement
    ports:
      - "3502:3502"
    networks:
      - dapr-network

  stats-service:
    build: .
    environment:
      - APP_MODULE=jokes-app.stats_service:app
      - APP_PORT=8004
    ports:
      - "8004:8004"
    networks:
      - dapr-network

  dapr-stats-service:
    image: "daprio/daprd:latest"
    command: >
      ./daprd --app-id stats-service --app-port 8004 --dapr-http-port 3503 --placement-host-address dapr-placement:50005
    depends_on:
      - stats-service
      - dapr-placement
    ports:
      - "3503:3503"
    networks:
      - dapr-network

  content-delivery-service:
    build: .
    environment:
      - APP_MODULE=jokes-app.content_delivery_service:app
      - APP_PORT=8005
    ports:
      - "8005:8005"
    networks:
      - dapr-network

  dapr-content-delivery-service:
    image: "daprio/daprd:latest"
    command: >
      ./daprd --app-id content-delivery-service --app-port 8005 --dapr-http-port 3504 --placement-host-address dapr-placement:50005
    depends_on:
      - content-delivery-service
      - dapr-placement
    ports:
      - "3504:3504"
    networks:
      - dapr-network

  frontend-gateway:
    build: .
    environment:
      - APP_MODULE=jokes-app.frontend_gateway:app
      - APP_PORT=8006
    ports:
      - "8006:8006"
    networks:
      - dapr-network

  dapr-frontend-gateway:
    image: "daprio/daprd:latest"
    command: >
      ./daprd --app-id frontend-gateway --app-port 8006 --dapr-http-port 3505 --placement-host-address dapr-placement:50005
    depends_on:
      - frontend-gateway
      - dapr-placement
    ports:
      - "3505:3505"
    networks:
      - dapr-network

networks:
  dapr-network:
    driver: bridge
